name: catatan_harian
description: Aplikasi Catatan Harian Sederhana
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  sqflite: ^2.2.8+4
  path: ^1.8.3
  intl: ^0.18.1
  provider: ^6.0.5
  lottie: ^2.7.0
  url_launcher: ^6.1.11
  google_fonts: ^5.1.0
  telephony: ^0.2.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/loading_animation.json